/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Describes the Car specification
 */
export interface Build { 
    /**
     * Year of the Car
     */
    year?: number;
    /**
     * Car Make
     */
    make?: string;
    /**
     * Car model
     */
    model?: string;
    /**
     * Trim of the car
     */
    trim?: string;
    /**
     * Body type of the car
     */
    bodyType?: string;
    /**
     * Vehicle type of the car
     */
    vehicleType?: string;
    /**
     * Drivetrain of the car
     */
    drivetrain?: string;
    /**
     * Fuel type of the car
     */
    fuelType?: string;
    /**
     * Made in of the car
     */
    madeIn?: string;
    /**
     * Engine of the car
     */
    engine?: string;
    /**
     * Engine block of the car
     */
    engineBlock?: string;
    /**
     * Engine size of the car
     */
    engineSize?: string;
    /**
     * Engine block of the car
     */
    engineMeasure?: string;
    /**
     * Engine aspiration of the car
     */
    engineAspiration?: string;
    /**
     * Transmission of the car
     */
    transmission?: string;
    /**
     * No of doors of the car
     */
    doors?: number;
    /**
     * No of cylinders of the car
     */
    cylinders?: number;
    /**
     * Steering type of the car
     */
    steeringType?: string;
    /**
     * Antibrake system of the car
     */
    antibrakeSys?: string;
    /**
     * Tank size of the car
     */
    tankSize?: string;
    /**
     * Overall height of the car
     */
    overallHeight?: string;
    /**
     * Overall length of the car
     */
    overallLength?: string;
    /**
     * Overall width of the car
     */
    overallWidth?: string;
    /**
     * Std seating of the car
     */
    stdSeating?: string;
    /**
     * Highway miles of the car
     */
    highwayMiles?: string;
    /**
     * City miles of the car
     */
    cityMiles?: string;
}
