/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Build } from './build';
import { Dealer } from './dealer';
import { ListingExtraAttributes } from './listingExtraAttributes';
import { ListingMedia } from './listingMedia';
import { Location } from './location';


/**
 * Represents a full list of attributes available with Marketcheck for a car
 */
export interface Listing { 
    /**
     * Unique identifier representing a specific listing from the Marketcheck database
     */
    id?: string;
    /**
     * Listing heading
     */
    heading?: string;
    /**
     * VIN for the car
     */
    vin?: string;
    /**
     * Stock no of the car
     */
    stockNo?: string;
    /**
     * Asking price for the car
     */
    price?: string;
    /**
     * MSRP for the car
     */
    msrp?: string;
    /**
     * Odometer reading / reported miles usage for the car
     */
    miles?: string;
    /**
     * Inventory type of car
     */
    inventoryType?: string;
    /**
     * Listing first seen at first scraped date
     */
    scrapedAtDate?: number;
    /**
     * Listing first seen at first scraped timestamp
     */
    firstSeenAt?: number;
    /**
     * Listing first seen at first scraped date
     */
    firstSeenAtDate?: string;
    /**
     * Vehicle Details Page url of the specific car
     */
    vdpUrl?: string;
    /**
     * Source domain of the listing
     */
    source?: string;
    /**
     * Flag indicating whether the car is Certified
     */
    isCertified?: number;
    /**
     * Days on Market value for the car based on current and historical listings found in the Marketcheck database for this car
     */
    dom?: number;
    /**
     * Days on Market value for the car based on current and last 6 month listings found in the Marketcheck database for this car
     */
    dom180?: number;
    /**
     * Days on Market value for the car based on current and last 30 days listings found in the Marketcheck database for this car
     */
    domActive?: number;
    /**
     * Seller type for the car
     */
    sellerType?: string;
    /**
     * Listing last seen at (most recent) timestamp
     */
    lastSeenAt?: number;
    /**
     * Listing last seen at (most recent) date
     */
    lastSeenAtDate?: string;
    /**
     * Build / Specifications attributes
     */
    build?: Build;
    /**
     * Car Media Attributes - main photo link/url and photo links
     */
    media?: ListingMedia;
    /**
     * Extra attributes for the listing - options, features, seller comments etc
     */
    extra?: ListingExtraAttributes;
    dealer?: Dealer;
    /**
     * Car location data. Included only if its a different location to the dealers location
     */
    carLocation?: Location;
}
