/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Build } from '../model/build';
import { Economy } from '../model/economy';
import { FuelEfficiency } from '../model/fuelEfficiency';
import { SafetyRating } from '../model/safetyRating';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class VINDecoderService {

    protected basePath = 'https://marketcheck-prod.apigee.net/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * VIN Decoder
     * Get the basic information on specifications for a car identified by a valid VIN
     * @param vin VIN to decode
     * @param apiKey The API Authentication Key. Mandatory with all API calls.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public decode(vin: string, apiKey?: string, observe?: 'body', reportProgress?: boolean): Observable<Build>;
    public decode(vin: string, apiKey?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Build>>;
    public decode(vin: string, apiKey?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Build>>;
    public decode(vin: string, apiKey?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (vin === null || vin === undefined) {
            throw new Error('Required parameter vin was null or undefined when calling decode.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (apiKey !== undefined) {
            queryParameters = queryParameters.set('api_key', <any>apiKey);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Build>(`${this.basePath}/vin/${encodeURIComponent(String(vin))}/specs`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Economy based on environmental factors
     * [MOCK] Calculate Economy i.e. Environmental Friendliness
     * @param vin VIN as a reference to the type of car for which Environmental Economy data is to be returned
     * @param apiKey The API Authentication Key. Mandatory with all API calls.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEconomy(vin: string, apiKey?: string, observe?: 'body', reportProgress?: boolean): Observable<Economy>;
    public getEconomy(vin: string, apiKey?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Economy>>;
    public getEconomy(vin: string, apiKey?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Economy>>;
    public getEconomy(vin: string, apiKey?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (vin === null || vin === undefined) {
            throw new Error('Required parameter vin was null or undefined when calling getEconomy.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (apiKey !== undefined) {
            queryParameters = queryParameters.set('api_key', <any>apiKey);
        }
        if (vin !== undefined) {
            queryParameters = queryParameters.set('vin', <any>vin);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Economy>(`${this.basePath}/economy`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get fuel effeciency
     * [MOCK] Calculate fuel efficiency from taxonomy db mileage values
     * @param vin VIN as a reference to the type of car for which fuel data is to be returned
     * @param apiKey The API Authentication Key. Mandatory with all API calls.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEfficiency(vin: string, apiKey?: string, observe?: 'body', reportProgress?: boolean): Observable<FuelEfficiency>;
    public getEfficiency(vin: string, apiKey?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<FuelEfficiency>>;
    public getEfficiency(vin: string, apiKey?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<FuelEfficiency>>;
    public getEfficiency(vin: string, apiKey?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (vin === null || vin === undefined) {
            throw new Error('Required parameter vin was null or undefined when calling getEfficiency.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (apiKey !== undefined) {
            queryParameters = queryParameters.set('api_key', <any>apiKey);
        }
        if (vin !== undefined) {
            queryParameters = queryParameters.set('vin', <any>vin);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<FuelEfficiency>(`${this.basePath}/fuel_efficiency`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Safety Rating
     * [MOCK] Get Safety ratings from third party sources
     * @param vin VIN to fetch the safety ratings
     * @param apiKey The API Authentication Key. Mandatory with all API calls.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSafetyRating(vin: string, apiKey?: string, observe?: 'body', reportProgress?: boolean): Observable<SafetyRating>;
    public getSafetyRating(vin: string, apiKey?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SafetyRating>>;
    public getSafetyRating(vin: string, apiKey?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SafetyRating>>;
    public getSafetyRating(vin: string, apiKey?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (vin === null || vin === undefined) {
            throw new Error('Required parameter vin was null or undefined when calling getSafetyRating.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (apiKey !== undefined) {
            queryParameters = queryParameters.set('api_key', <any>apiKey);
        }
        if (vin !== undefined) {
            queryParameters = queryParameters.set('vin', <any>vin);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<SafetyRating>(`${this.basePath}/safety`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
